;
; Sagewood Dark Theme
;

; Base Dark Tones (Crust & Canvas)
sagewood0=#222a26
sagewood1=#2d3833
sagewood2=#3b4a43
sagewood3=#677a70

; Text Tones (Milky Mint-Cream)
sagewood4=#d2ded7
sagewood5=#d2ded7
sagewood6=#ffffff

; Accents (Cyan, Blue, Green, Rose, Yellow, Magenta)
sagewood7=#9bb5b1
sagewood8=#9bb5b1
sagewood9=#8da7b3
sagewood10=#8da7b3
sagewood11=#d99c82
sagewood12=#d99c82
sagewood13=#d6caa3
sagewood14=#3b4a43
sagewood15=#caacc2

base50_text50=#819187
base70_text30_mix=#5f7067
sagewood8_semi=#809bb5b1
sagewood10_semi=#808da7b3

[palette]
base=$sagewood0
text=$sagewood4

window=$sagewood1
window_text=$sagewood5

button=$sagewood2
button_text=$sagewood6

highlight=$sagewood14
highlight_text=$sagewood6

; 80 base 20 text
placeholder_text=$base50_text50

link=$sagewood9
link_visited=$sagewood15

[window]
;window_shadow_brush=
;window_background_brush=
;window_border_brush=
;input_background_brush=transparent
;input_border_brush=
;input_trigger_color=$sagewood8
;input_hint_color=$sagewood7
;settings_button_color=
;settings_button_highlight_color=
;result_item_selection_background_brush=$sagewood10_semi
;result_item_selection_border_brush=transparent
;result_item_selection_text_color=$palette/button_text
;result_item_selection_subtext_color=$palette/placeholder_text
;result_item_text_color=$palette/placeholder_text
;result_item_subtext_color=$sagewood3
;action_item_selection_background_brush=
;action_item_selection_border_brush=
;action_item_selection_text_color=
;action_item_text_color=
